# Generated by Django 5.2.1 on 2025-05-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('escolaridade', models.CharField(max_length=30)),
                ('idiomas', models.CharField(max_length=100)),
                ('experiencia', models.CharField(max_length=3000)),
                ('apelido', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Usuaria',
                'ordering': ['apelido'],
            },
        ),
    ]
