# Generated by Django 5.2.2 on 2025-06-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuaria',
            name='experiencia',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='usuaria',
            name='idiomas',
        ),
        migrations.AddField(
            model_name='usuaria',
            name='idiomas',
            field=models.ManyToManyField(to='usuaria.idioma'),
        ),
    ]
