# Generated by Django 4.2.23 on 2025-06-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaria', '0004_usuaria_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuaria',
            name='senha',
        ),
    ]
