# Generated by Django 5.2.1 on 2025-05-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('seguimento', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=7)),
                ('contato', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'ordering': ['nome', 'seguimento'],
            },
        ),
    ]
