# Generated by Django 4.2.23 on 2025-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_cnpj_alter_empresa_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='senha',
            field=models.CharField(default='senha123', max_length=100),
        ),
    ]
