# Generated by Django 4.2.23 on 2025-06-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0003_empresa_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='senha',
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
