# Generated by Django 4.2.23 on 2025-06-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_remove_empresa_senha_empresa_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='contato',
            new_name='email',
        ),
    ]
